add support for forcing push

diff --git a/.github/workflows/build-dockerfile.yml b/.github/workflows/build-dockerfile.yml
--- a/.github/workflows/build-dockerfile.yml
+++ b/.github/workflows/build-dockerfile.yml
@@ -27,6 +27,10 @@ on:
         required: false
         type: boolean
         default: false
+      force-push:
+        required: false
+        type: boolean
+        default: false
     secrets:
       registry-user:
         required: true
@@ -59,8 +63,16 @@ jobs:
         TAG=$REGISTRY/$IMAGE_NAME:$TAG
 
         # determine if we should push the image
-        PUSH=false
-        if [[ "$REQUESTED_SUPPRESS_PUSH" != "true" ]]; then
+        if [[ "$REQUESTED_FORCE_PUSH" == "true" ]] && [[ "$REQUESTED_SUPPRESS_PUSH" == "true" ]]; then
+          echo "You cannot force and suppress push at the same time."
+          exit 1
+        fi
+        PUSH=
+        if [[ "$REQUESTED_FORCE_PUSH" == "true" ]]; then
+          PUSH=true
+        elif [[ "$REQUESTED_SUPPRESS_PUSH" == "true" ]]; then
+          PUSH=false
+        else
           if [[ "$EVENT_NAME" == "push" ]] || [[ "$EVENT_NAME" == "schedule" ]]; then
             if [[ "$REF_NAME" == "$DEFAULT_BRANCH" ]] || [[ $REF_TYPE == "tag" ]]; then
               PUSH=true
@@ -74,6 +86,7 @@ jobs:
       env:
         REQUESTED_TAG: ${{ inputs.tag }}
         REQUESTED_SUPPRESS_PUSH: ${{ inputs.suppress-push }}
+        REQUESTED_FORCE_PUSH: ${{ inputs.force-push }}
         REGISTRY: ${{ inputs.registry-host }}
         REF_NAME: ${{ github.ref_name }}
         REF_TYPE: ${{ github.ref_type }}
